project_id = "qzwxisdfwswsrbzvpzlo"

[functions.generate-survey-analysis]
verify_jwt = false

[functions.chat-with-survey-data]
verify_jwt = false

[functions.generate-filtered-analysis]
verify_jwt = false
